version: '2'

services:
    web:
        build: ./nginx
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./res/code:/code
        networks:
            - code-network
    php:
        build: ./php
        container_name: php
        volumes:
            - ./res/code:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
